try {
  throw "It's a test.";
} catch (e) {
  console.log(e);
}
